### PR TITLE
Devel enbo

### PR DESCRIPTION
**Pull request by zhouenbo**
This branch implements SegNet to map river network on Greenland Ice Sheet. Codes include three parts, namely DataPreparation_segnet.py to prepare training data, training_segnet.py to train the SegNet, and prediction_segnet.py to make predictions for new images. 

To use these codes, users just need to set the path for model and image,  and run prediction_segnet.py for predicitons.

The sample images and model are upload into google drive for the rivers.

### CODE REVIEW

**Comment by zhouenbo** [comment]
ExtractResult1.JPG is prediction from a WorldView image. If it needs to be deleted, pls do it.

**Comment by bspitzbart** [comment]
Great! Looks good. We will review by early next week.

**Comment by bspitzbart** [comment]
Hello @zhouenbo This looks very well done and is organized and easy to read.
My main comment is that we will require all hard-coded filenames and paths be replaced with input parameters.  That is, the user specifies an input directory on the command line and all .tif files in that directory are processed.
TEST_SET = ['12JUL181553195.tif','12JUL181553219.tif','12JUL211543217.tif','12JUL211543228.tif','12JUL211543239.tif']
base_directory = 'D:\\RiversTraining\\TwoClasses\\'

To be consistent with the other ICEBERG projects, try to use argparse (https://docs.python.org/3/library/argparse.html)

**Comment by bspitzbart** [comment]
Also, do you intend to include training at this time or should we focus on using the model or models you have already trained to let users do the prediction on new images?  We can add the training pipeline later if that is something general users can use.

**Comment by zhouenbo** [comment]
> Also, do you intend to include training at this time or should we focus on using the model or models you have already trained to let users do the prediction on new images? We can add the training pipeline later if that is something general users can use.

OK, I will use the argparse to get user's parameters. At this time, I think we focus on using models to do predictions. We can add training and preprocessing procedures later.

**Comment by iparask** [comment]
Hello @zhouenbo, can you update the README file in your branch? I would like to run it on Bridges and see how I can replicate your results. Also, can you include a section with the necessary packages to run your code? 
Thank you!

**Comment by iparask** [comment]
The PR remains open.

**Comment by iparask** [comment]
Ask @venachu how to proceed with this PR.

**Pull request closed without merging**
